repos:
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black
      args: ["--line-length", "120"]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files", "--line-length", "120"]
- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
    - id: flake8
      args:
      - "--max-line-length=120"
      - "--max-complexity=21"
      - "--select=B,C,E,F,W,T4,B9"
      # these are errors that will be ignored by flake8
      # https://flake8.pycqa.org/en/latest/user/error-codes.html
      - "--ignore=E203,E266,E501,W503,F403,F401,E402,E731"
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.24.0
  hooks:
    - id: commitizen
      stages:
        - commit-msg